### ISSUE TITLE
[AWS] Support CloudFront Service

### ISSUE THREAD

**Issue by aquamatthias** [someengineering/resoto#1173]
### Motivation

Collect [AWS CloudFront](https://aws.amazon.com/cloudfront) resources as part of the AWS collect cycle.

### Desired Behavior

Implement the resource collector as part of the [aws](https://github.com/someengineering/resoto/tree/main/plugins/aws) collector. To get an idea how a collector looks like, take the [SQS](https://github.com/someengineering/resoto/blob/main/plugins/aws/resoto_plugin_aws/resource/sqs.py) resource as inspiration. 

For further explanation and guidance, please visit the [Resource Guide](https://resoto.com/docs/edge/contributing/plugins/aws).

**Comment by K4ngar0o** [comment]
Hey @aquamatthias - I read through this comment and I would like to tackle this implementation - can you assign this to me?

**Comment by aquamatthias** [comment]
Hey @K4ngar0o - sounds good! In case of questions, consider to join our discord channel: https://discord.gg/someengineering

**Comment by anjafr** [comment]
done with #1350
