### ISSUE TITLE
Setup wizard confusing question

### ISSUE THREAD

**Issue by alanmcg** [someengineering/resoto#1379]
### Description

![image](https://user-images.githubusercontent.com/43033315/214569134-3f9ff6e9-0fd9-445f-9053-62905038f210.png)
This is not a YES | NO question so the correct option to select is down to guesswork

### Version

latest

### Steps to Reproduce

Follow initial steps in this quick start documentation https://resoto.com/docs/getting-started/install-resoto/docker

**Comment by RPicster** [comment]
Thanks for the report, this was fixed with the following PR:
https://github.com/someengineering/resoto/issues/1379
