### ISSUE TITLE
[keepercore] - allow dynamic CLI aliases

### ISSUE THREAD

**Issue by lloesche** [someengineering/resoto#169]
From user feedback on Discord:

Queries like `is(aws_alb) and ctime<"-7d" and backends==[] with(empty, <-- is(aws_alb_target_group) and target_type=="instance" and ctime<"-7d" with(empty, <-- is(aws_ec2_instance) and instance_status!="terminated")) <-[0:1]- is(aws_alb_target_group) or is(aws_alb)` are powerful but also complex.

Chat protocol:
```
ViktorHarutyunyan:
I am not sure what's the target audience but I think this is an overkill, I think a simple query like:
> ck show unused lbs
then there should be like a man page explaining the criteria of selection. 
then the user can choose to say -r region -a account etc.. 
or say --days=7
imo, this is much simpler 
then if we talk about UI, then it is all clicks and nice small value edit windows. 
ck show unused tgs .... 
ck show unattached volumes ....
```

The CLI already has aliases. We should make those configurable so that users can download/exchange other users aliases. So the complex query above could turn into `show unused loadbalancers`.

Personally I'd also not want to have to type the complex query even if I know the syntax. A shorthand form would be useful.

**Comment by aquamatthias** [comment]
2.0.0a9 ships with a query template engine. This allows defining complex queries and store them in the library under a given name. A query can now expand and execute this query.
```
> templates add old_load_balancer is(load_balancer) and reported.age > {{old}}
Template old_load_balancer added to the query library.
is(load_balancer) and reported.age > {{old}}
> query expand(old_load_balancer, old=3w)
```

It is not a dynamic CLI alias, but solves the original problem of managing complex queries.
I would opt to close this ticket.
