### ISSUE TITLE
[docker] better defaults on many-core machines

### ISSUE THREAD

**Issue by lloesche** [someengineering/resoto#372]
Right now the defaults in our Docker image are not to fork collector plugins and collect 2 accounts simultaneously. This is great for testing Cloudkeeper on a personal Laptop but not for a many-core server. The image should detect the environment it is running in and the amount of resources available to it and automatically scale to higher settings by default.

**Comment by jplourenco1** [comment]
Hi, I would like to help on this. Can you point me in what file these two operations (fork collector plugins and collect 2 accounts) are being done?

**Comment by lloesche** [comment]
The best place is likely here:
https://github.com/someengineering/cloudkeeper/blob/main/docker/bootstrap#L143-L153
https://github.com/someengineering/cloudkeeper/blob/main/docker/defaults#L57
https://github.com/someengineering/cloudkeeper/blob/main/docker/common

Relevant `ckworker` variable names and their defaults are:
```
CKWORKER_FORK=false
CKWORKER_AWS_FORK=false
CKWORKER_GCP_FORK=false
CKWORKER_AWS_ACCOUNT_POOL_SIZE=5
CKWORKER_GCP_PROJECT_POOL_SIZE=5
```

In `bootstrap` export those variables, in `common` implement the number of CPU cores detection and in `defaults` set the ckworker variables to some sane values.

E.g.
```
num_cores=$(get_num_cores)
if [ $num_cores -gt 4 ]; then
    CKWORKER_FORK=${CKWORKER_FORK:-true}
    ...
    ...
else
    CKWORKER_FORK=${CKWORKER_FORK:-false}
    ...
    ...
fi
```
something along those lines. The pool size determines how many processes will be forked / how many accounts/projects will be collected in parallel.
