### ISSUE TITLE
Enable notification as ckcore command.

### ISSUE THREAD

**Issue by aquamatthias** [someengineering/resoto#502]
### Scenario cleanup

cloudkeeper is able to cleanup resources.
While this is a great feature - it requires trust to enable this feature.
A first step  to gain trust, might be a notification option: instead of cleaning the resources, a message is send, that informs me about the resources that would have been deleted.
This does not require any write/delete permissions.
People can review the list and act themselves.

### Scenario rule enforcement

Rules can be encoded as queries (matching items break the rule).
It would be great to have a simple way to ping people if rules are broken.

### Message channels

Ideally we would support email, slack and discord.
The command should allow for a list of recipients.

### ckworker/cknotify

The notification is issued by ckcore via a command. The command would use the `Task` infrastructure, so a dedicated
worker can do this task. Unclear if the functionality would be implemented in ckworker or if we need a separate component.

## Considerations

- the notification command should allow for a list of recipients.
- either we have one `notify` command that allows for different communication channels, or we have dedicated commands like `slack`, `email`, `discord`...
- maybe we could also use information of the collected resource (like owner etc) to send a message to this person.

**Comment by TheCatLady** [comment]
Why would we send a notification on an action that did not occur?  Doesn't simply printing the output to the terminal (or writing to a log file) make more sense in the case of dry runs?

That said, I think there would be value in webhook support here.  That would allow the execution of whatever custom logic a user wants, either in addition to or in lieu of the built-in cleanup.

**Comment by aquamatthias** [comment]
> Why would we send a notification on an action that did not occur? Doesn't simply printing the output to the terminal (or writing to a log file) make more sense in the case of dry runs?

1) The dry run flag is system level: either it is enabled or not: there can be scenarios where some resources are cleaned up and some want the "dry run" (experimenting with the config etc.).

2) Also: changing the dry run flag requires access to the installation. This is not necessarily the case in all environments.

3) notifications enable other use cases. See my rule enforcement example: people get notified if a rule is violated. The action that needs to performed is manifold (cleaning up might be wrong). A notification would allow custom human intervention.


> That said, I think there would be value in webhook support here. That would allow the execution of whatever custom logic a user wants, either in addition to or in lieu of the built-in cleanup.

Totally agree. Please see #149 for dedicated web hook support. This issue here is for human intervention using a communication channel like email, slack, discord, etc.

**Comment by TheCatLady** [comment]
> 1. The dry run flag is system level: either it is enabled or not: there can be scenarios where some resources are cleaned up and some want the "dry run" (experimenting with the config etc.).
> 2. Also: changing the dry run flag requires access to the installation. This is not necessarily the case in all environments.
> 3. notifications enable other use cases. See my rule enforcement example: people get notified if a rule is violated. The action that needs to performed is manifold (cleaning up might be wrong). A notification would allow custom human intervention.

I'm not saying that there is no reason for notification support, but "dry run" functionality is not justification for notifications.  That would be a band-aid patch for the issue that the dry run flag is not supported at the command level rather than the install level.

Notifications where an action/event has occurred (especially if human intervention is needed) would be a good use case for notifications.

**Comment by aquamatthias** [comment]
resotocore now has alias templates.
It ships with one example of how to use notifications to discord, while it is possible to talk to slack, alertmanager etc.
