### ISSUE TITLE
Build separate Docker images for each component

### ISSUE THREAD

**Issue by TheCatLady** [someengineering/resoto#528]
### Motivation

The existing Docker image contains all components, and does not allow a user to only "install" the components they need.

### Desired Behavior

Build Docker images for each component of Cloudkeeper.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by aquamatthias** [comment]
@TheCatLady The separate images get pushed with every commit to main. The information is missing in our docs. Can you take care?

**Comment by TheCatLady** [comment]
> @TheCatLady The separate images get pushed with every commit to main. The information is missing in our docs. Can you take care?

Yup!  Let's close this issue since it's been resolved on the product side and open a new issue on the website repo.
