### ISSUE TITLE
Create Helm Chart repository

### ISSUE THREAD

**Issue by TheCatLady** [someengineering/resoto#529]
### Motivation

Currently, the Helm Chart needs to be pulled from the GitHub repository.

### Desired Behavior

The Helm Chart should be published in a repository.

### Code of Conduct

- [X] I agree to follow the Code of Conduct

**Comment by cebidhem** [comment]
HI @TheCatLady I just discovered your project Resoto which is great!

If you'd like, I'm keen to set-up the actions to publish the Helm chart in a GitHub Pages chart repo.
However I'd need you to create a `helm-charts` repository in your organization.

**Comment by TheCatLady** [comment]
Hi @cebidhem, that would be awesome! someengineering/helm-charts has been created.

**Comment by cebidhem** [comment]
Thanks @TheCatLady ! I'm sorry but I guess I'll also need a `gh-pages` branch in the `helm-charts` project to push the index.

FYI I'll be afk for about two weeks with no laptop, so if it's not too urgent I'll work on it as soon as I come back!

**Comment by kushthedude** [comment]
Hey @cebidhem @TheCatLady , do you mind if I pick this issue?

**Comment by cebidhem** [comment]
Hi @kushthedude it is fine for me, haven't had time since I came back so feel free to take it.

**Comment by kushthedude** [comment]
@TheCatLady can we close this?
