### ISSUE TITLE
Replace merge_with_ancestors by merge query

### ISSUE THREAD

**Issue by aquamatthias** [someengineering/resoto#576]
### Motivation

`merge_with_ancestors` was introduced as a preliminary solution.

### Desired Behavior

Use merge query instead.

### Additional Context

Usages found:
```
resotocore/core/cli/command.py
resotocore/core/db/arango_query.py
resotocore/core/query/query_parser.py
resotocore/tests/core/db/graphdb_test.py
resotocore/tests/core/query/__init__.py
resotocore/tests/core/query/query_parser_test.py
resotolib/resotolib/baseresources.py
resotolib/build/lib/resotolib/baseresources.py
```

**Comment by lloesche** [comment]
No longer being used in baseresources, moved all metrics generation to the new `/ancestors` section.
