### ISSUE TITLE
[resotocore] return edge type with graph

### ISSUE THREAD

**Issue by lloesche** [someengineering/resoto#629]
### Motivation

When sending a graph to the core you define `edge_type` for each edge. When querying a graph from the core the `edge_type` is missing as only the one type that was requested in the query gets returned. To restore the original edge type (without having to propagate part of the query to the edge creator) this information would be important.

### Desired Behavior

Return `edge_type` as part of the edge.

**Comment by aquamatthias** [comment]
Implemented via #649
