### ISSUE TITLE
[resotocore] Help text is hard to read in Ubuntu Terminal

### ISSUE THREAD

**Issue by iainelder** [someengineering/resoto#652]
### Description

In logs section I've pasted a text version of this screenshot.

The screenshot shows how the text renders with colors in Ubuntu Terminal.

The messages that start with hashes such as "# Show all available kinds." are almost impossible to read because the background is dark blue and the text is slightly darker blue.

![image](https://user-images.githubusercontent.com/5024311/153720084-909b461a-09ec-4876-bad7-783a0ac1cd08.png)

### Version

2.0.0a16

### Environment

Ubuntu 20.04.3 LTS

### Steps to Reproduce

1. Start an Ubuntu Terminal session.
2. Start resh using `docker run`.
3. Run a help command such as `help kind`.
4. Struggle to see the darker blue text on a dark blue background.

### Logs

```shell
> help kind
kind: Retrieves information about the graph data kinds.                                                  

┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ kind [-p property_path] [name]                                                                        │
└───────────────────────────────────────────────────────────────────────────────────────────────────────┘

kind gives information about the available graph data kinds.                                             


                                                 Options                                                 

 • -p [Optional] property_path: lookup the kind for the defined property path. This will do a reverse    
   lookup and search all kinds for the specified property path.                                          


                                               Parameters                                                

 • name [Optional]: show available information about the kind with provided name.                        


                                                Examples                                                 

┌───────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                       │
│ # Show all available kinds.                                                                           │
│ > kind                                                                                                │
│ access_key                                                                                            │
│ .                                                                                                     │
│ .                                                                                                     │
│ zone                                                                                                  │
│                                                                                                       │
│ # Show details about a specific kind.                                                                 │
│ > kind graph_root                                                                                     │
│ name: graph_root                                                                                      │
│ bases:                                                                                                │
│ - graph_root                                                                                          │
│ properties:                                                                                           │
│ - description: The name of this node.                                                                 │
│   kind: string                                                                                        │
│   name: name                                                                                          │
│   required: false                                                                                     │
│ - description: All attached tags of this node.                                                        │
│   kind: dictionary[string, string]                                                                    │
│   name: tags                                                                                          │
│   required: false                                                                                     │
│                                                                                                       │
│ # Lookup the type of the given property path in the model.                                            │
│ > kind -p reported.tags.owner                                                                         │
│ name: string                                                                                          │
│ runtime_kind: string                                                                                  │
└───────────────────────────────────────────────────────────────────────────────────────────────────────┘
>
```

**Comment by aquamatthias** [comment]
@iainelder thanks for the report. We need to take a look into the color scheme. 
As a workaround for the time being: you can start the resotoshell with the `--no-color` option.

**Comment by aquamatthias** [comment]
I installed ubuntu and tried myself.

<img width="339" alt="image" src="https://user-images.githubusercontent.com/330485/154041195-7640f0be-d2cb-444f-8435-7d2298d29b75.png">

My terminal supports 256 colors. Above detail looks like this.
```
> echo $TERM
xterm-256color
```

Rendered with standard colors it looks like this:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/330485/154042040-7cd10497-f5a0-42dc-b658-bbdeaab0e862.png">
which seems to be close to unreadable.

@iainelder What kind of terminal do you have (what is the TERM env set to?). 

I would propose a change, which would look like this:

Standard:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/330485/154042179-344f0e72-8781-45f2-b514-0ceb2103e03f.png">

256 Colors:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/330485/154042298-4049bc0e-80dd-4280-ac18-d570e1973a29.png">

True Colors:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/330485/154042413-b6936264-1f37-4b6b-9472-fc70c8a77e94.png">

**Comment by iainelder** [comment]
I should add that I'm running all the resh commands in the Docker container version version resoto:2.0.0a16.

> @iainelder What kind of terminal do you have (what is the TERM env set to?).

In my Ubuntu terminal:

```
$ echo $TERM
xterm-256color
```

In the resoto Docker container:

```
root@e909714648ba:/# echo $TERM
xterm
```

If in the container I set `TERM=xterm-256color` then the output is more readable.

![image](https://user-images.githubusercontent.com/5024311/154077958-a1497def-ee44-4891-ae0c-882fa2058e83.png)

Does the default setting in the container need to be changed?

**Comment by aquamatthias** [comment]
Mmh typically the `TERM` variable should be set by the terminal emulator. 
In case of docker, it will set the TERM variable to xterm (see [environment-variables](https://docs.docker.com/engine/reference/run/#env-environment-variables))
When exec into the docker container you can define env vars like: `-eTERM` - this will set the env var to the current value.

@lloesche any other idea?
