### ISSUE TITLE
[resotocore] add CSV and markdown table output format

### ISSUE THREAD

**Issue by lloesche** [someengineering/resoto#653]
### Motivation

From Discord discussion:
```
@isme: CSV output would certainly be useful because it's a format that pretty much every analysis tool supports.

But sometimes, as in the above example, I just use CSV as a "staging" format so that I can render a table using csvlook. A table is often the most readable way to present results.

So if resh also had a table format it would save a lot of manual labor. You'd get bonus points if the table output was in Github syntax because then you could immediately paste it into a Markdown document or Github issue.
```

### Desired Behavior

Have a CSV format output, including header, as well as markdown pre-formated table output.

**Comment by iainelder** [comment]
In the Discord chat I showed how I would generate a Markdown table using `csvlook`.

I just discovered a more convenient way using `jtbl`. It skips the CSV staging part so there's no need to faff about with `--no-inference` options in csvkit.

https://github.com/kellyjonbrazil/jtbl

It doesn't seem to support Markdown-formatted tables yet, so I opened an issue for that.

https://github.com/kellyjonbrazil/jtbl
