### ISSUE TITLE
[resotoworker] Cleanup event is logged as error if cleanup is turned off

### ISSUE THREAD

**Issue by lloesche** [someengineering/resoto#724]
### Description

Right now the worker will log
```
22-03-22 13:00:57|resotoworker|ERROR|59|worker-collect_cleanup  No graph root found - unable to sanitize
22-03-22 13:00:57|resotoworker|ERROR|59|worker-collect_cleanup  Cleanup called but --cleanup flag not provided at startup - ignoring call
```
when a `cleanup` action is received but `--cleanup` isn't supplied to the worker. This should just be debug or info. It was error in Resoto v1.0 but the way cleanup is triggered has changed in 2.0.

### Version

2.0.0a17

**Comment by aquamatthias** [comment]
Fixed via #750
