### ISSUE TITLE
Tags were not collected on an S3 bucket

### ISSUE THREAD

**Issue by meln1k** [someengineering/resoto#808]
### Description

S3 bucket did not have any tags collected despite the fact that they were present in AWS console.

### Version

1bcf470d4609d1d49c7f5f2cd21e42c3fe8df0d2

### Environment

m1 mac, arango 3.8

### Additional Context

That happened during the setup call with Yann from our discord.

**Comment by aquamatthias** [comment]
Fixed via #847
