### ISSUE TITLE
Using the volume mount of aws credentials tries to change ownership of the creds files

### ISSUE THREAD

**Issue by tfmm** [someengineering/resoto#978]
### Description

When running the provided docker-compose from the docs, and volume mounting the aws credentials as instructed, resotoworker tries to change ownership of these files. This is a destructive operation if these files are not owned by root already. 

Mounting credentials via a RO volume mount would be preferred, however if doing this, the container fails to start. 

### Version

2.3

### Environment

MacOS x86

### Steps to Reproduce

1. Follow docs at https://resoto.com/docs/getting-started/installation/docker to create environment to run resoto with docker
2. setup resotoworker to volume mount credentials as instructed in the docs
3. Resoto worker then attempts to change ownership of these existing files. 

### Logs

```shell
INFO - Setting uid:gid of resoto to 0:0
chown: changing ownership of '/home/resoto/.aws/config': Read-only file system
chown: changing ownership of '/home/resoto/.aws/credentials': Read-only file system
chown: changing ownership of '/home/resoto/.aws': Read-only file system
```

**Comment by lloesche** [comment]
@tfmm thank you for the report! That's indeed a bug, that we introduced with the ability to run the container as non-root user.
